"""PDF and DOCX export for impact assessments."""

import io
from datetime import datetime

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Pt
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
)

from api.models import AISystem, ImpactAssessment


# -- Helpers ---------------------------------------------------------------


def _display_value(value) -> str:
    if value is None:
        return "(Not provided)"
    if isinstance(value, bool):
        return "Yes" if value else "No"
    return str(value)


def _safe_filename(name: str) -> str:
    """Sanitize a string for use in filenames."""
    return "".join(c if c.isalnum() or c in " -_" else "_" for c in name).strip()


# -- PDF Export ------------------------------------------------------------


def export_assessment_pdf(
    assessment: ImpactAssessment, system: AISystem
) -> io.BytesIO:
    """Generate a PDF of the completed impact assessment."""
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        topMargin=72,
        bottomMargin=72,
        leftMargin=72,
        rightMargin=72,
    )
    styles = getSampleStyleSheet()

    # Custom styles
    field_label_style = ParagraphStyle(
        "FieldLabel",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=10,
        spaceAfter=2,
    )
    field_value_style = ParagraphStyle(
        "FieldValue",
        parent=styles["Normal"],
        fontSize=10,
        spaceAfter=8,
        leftIndent=12,
    )
    section_desc_style = ParagraphStyle(
        "SectionDesc",
        parent=styles["Normal"],
        fontSize=9,
        textColor="#666666",
        spaceAfter=8,
        fontName="Helvetica-Oblique",
    )

    story: list = []

    # Cover page
    story.append(Spacer(1, 1.5 * inch))
    story.append(Paragraph("AI System Impact Assessment", styles["Title"]))
    story.append(Spacer(1, 24))
    story.append(Paragraph(f"System: {system.name}", styles["Heading2"]))
    story.append(
        Paragraph(
            f"Risk Tier: {system.risk_tier.value.upper()}", styles["Heading3"]
        )
    )
    story.append(Spacer(1, 12))
    story.append(Paragraph(f"Assessment: {assessment.title}", styles["Heading3"]))
    story.append(
        Paragraph(f"Status: {assessment.status.value.replace('_', ' ').title()}",
                  styles["Normal"])
    )
    story.append(
        Paragraph(
            f"Created: {assessment.created_at.strftime('%Y-%m-%d')}",
            styles["Normal"],
        )
    )
    if assessment.assessor_name:
        story.append(
            Paragraph(f"Assessor: {assessment.assessor_name}", styles["Normal"])
        )
    if assessment.approved_by:
        story.append(
            Paragraph(f"Approved by: {assessment.approved_by}", styles["Normal"])
        )

    story.append(PageBreak())

    # Render sections
    content = assessment.content or {}
    sections = content.get("sections", [])
    for section in sections:
        story.append(Paragraph(section["title"], styles["Heading2"]))
        if section.get("description"):
            story.append(Paragraph(section["description"], section_desc_style))
        story.append(Spacer(1, 6))

        for field in section.get("fields", []):
            label = field["label"]
            if field.get("required"):
                label += " *"
            story.append(Paragraph(label, field_label_style))
            story.append(
                Paragraph(_display_value(field.get("value")), field_value_style)
            )

        story.append(Spacer(1, 12))

    # Footer
    story.append(Spacer(1, 24))
    footer_style = ParagraphStyle(
        "Footer",
        parent=styles["Normal"],
        fontSize=8,
        textColor="#999999",
        alignment=1,  # center
    )
    story.append(
        Paragraph(
            f"Generated by AI Governance Register on "
            f"{datetime.now(tz=None).strftime('%Y-%m-%d %H:%M UTC')}",
            footer_style,
        )
    )

    doc.build(story)
    buffer.seek(0)
    return buffer


# -- DOCX Export -----------------------------------------------------------


def export_assessment_docx(
    assessment: ImpactAssessment, system: AISystem
) -> io.BytesIO:
    """Generate a DOCX of the completed impact assessment."""
    doc = Document()

    # Cover info
    title = doc.add_heading("AI System Impact Assessment", level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    doc.add_paragraph(f"System: {system.name}")
    doc.add_paragraph(f"Risk Tier: {system.risk_tier.value.upper()}")
    doc.add_paragraph(f"Assessment: {assessment.title}")
    doc.add_paragraph(
        f"Status: {assessment.status.value.replace('_', ' ').title()}"
    )
    doc.add_paragraph(f"Created: {assessment.created_at.strftime('%Y-%m-%d')}")
    if assessment.assessor_name:
        doc.add_paragraph(f"Assessor: {assessment.assessor_name}")
    if assessment.approved_by:
        doc.add_paragraph(f"Approved by: {assessment.approved_by}")

    doc.add_page_break()

    # Render sections
    content = assessment.content or {}
    sections = content.get("sections", [])
    for section in sections:
        doc.add_heading(section["title"], level=1)
        if section.get("description"):
            desc_para = doc.add_paragraph()
            run = desc_para.add_run(section["description"])
            run.italic = True
            run.font.size = Pt(9)

        for field in section.get("fields", []):
            p = doc.add_paragraph()
            label = field["label"]
            if field.get("required"):
                label += " *"
            run = p.add_run(f"{label}: ")
            run.bold = True
            p.add_run(_display_value(field.get("value")))

        doc.add_paragraph()  # Spacer

    # Footer
    doc.add_page_break()
    footer_para = doc.add_paragraph()
    footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = footer_para.add_run(
        f"Generated by AI Governance Register on "
        f"{datetime.now(tz=None).strftime('%Y-%m-%d %H:%M UTC')}"
    )
    run.italic = True
    run.font.size = Pt(8)

    buffer = io.BytesIO()
    doc.save(buffer)
    buffer.seek(0)
    return buffer


def get_export_filename(
    system: AISystem, assessment: ImpactAssessment, extension: str
) -> str:
    """Build a safe filename for an export."""
    name = _safe_filename(system.name)
    date_str = assessment.created_at.strftime("%Y%m%d")
    return f"assessment_{name}_{date_str}.{extension}"
